version: "3.8"
services:
  postgres:
    container_name: devorum
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devorum
      PGDATA: /data/postgres
    volumes:
      - .data/pg:/data/postgres

  # redis:
  #   container_name: devorum-cache
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./data/redis:/data
