###
GET http://localhost:8080/login
Content-Type: application/json

{
  "name": "Luan Victor",
  "password": "123456"
}

###
GET http://localhost:8080/questions

###
GET http://localhost:8080/comments/2b21a907-abc0-47b7-898a-9c3f18e39702

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "name": "Luan Victor",
  "contact": "lvictor7",
  "password": "123456"
}

###
POST http://localhost:8080/questions
Content-Type: application/json

{
  "author_id": "be43abbb-3e9b-4217-ba3d-788289b70e1a",
  "title": "Dêem alusão do que são métodos de arrays",
  "question": "Como posso definir o que são ou como posso trazer para o mundo real o que são os métodos de array?"
}

###
POST http://localhost:8080/questions/comments
Content-Type: application/json

{
  "author_id": "b9e044c2-2d6f-4b1e-8d6e-e6db36dfe249",
  "question_id": "2b21a907-abc0-47b7-898a-9c3f18e39702",
  "comment": "Irmão, basta olhar as aulas do curso que já vão te ensinar o bastante (ja que pelo visto vc nao se deu o trabalho de olhar) ou vai procurar usando o google ou chatgpt. Se vira e aprende."
}

###
DELETE http://localhost:8080/comments/605835c8-d13a-413a-859f-b0385dfc4cca

###
DELETE http://localhost:8080/questions/12ad50e2-d039-4afa-9e6d-2fa1e73cc2ec

###
DELETE http://localhost:8080/users/87f4564e-6420-41ac-b17a-b54849c87e54

